services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false

  seed-yadav_consulting:
    build: ./seed-scripts
    volumes:
      - ./resources:/usr/src/app/data    
    depends_on:
      - mongo
    env_file:
      - ./envs/yadav_consulting.env
    command: ["npm", "run", "seed-yadav_consulting"]

  seed-rozgaar_setu:
    build: ./seed-scripts
    volumes:
      - ./resources:/usr/src/app/data
    depends_on:
      - mongo
    env_file:
      - ./envs/rozgaar_setu.env
    command: ["npm", "run", "seed-rozgaar_setu"]
    
  backend-yadav_consulting:
    build: ./backend/yadav_consulting
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - mongo-express
      - seed-yadav_consulting
    env_file:
      - ./envs/yadav_consulting.env

  backend-rozgaar_setu:
    build: ./backend/rozgaar_setu
    ports:
      - 4000:4000
    depends_on:
      - mongo
      - mongo-express
      - seed-rozgaar_setu
    env_file:
      - ./envs/rozgaar_setu.env

  transformation-engine:
    build: ./transformation-engine
    env_file:
      - ./envs/mcp_server.env
    depends_on:
      - mongo
      - mongo-express
      - backend-rozgaar_setu
      - backend-yadav_consulting
    command: ["npm", "run", "transform"]

  mcp-backend:
    build: ./transformation-engine
    env_file:
      - ./envs/mcp_server.env
    ports:
      - 6000:6000
    depends_on:
      - mongo
      - mongo-express
      - backend-rozgaar_setu
      - backend-yadav_consulting
    command: ["npm", "run", "dev"]

  frontend_company_a:
    build: ./company/frontend/company-a/blue-collar-careers-main
    container_name: frontend-company-a
    ports:
      - 8080:8080
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend-a

  frontend_company_b:
    build: ./company/frontend/company-b/dark-hued-careers-portal
    container_name: frontend-company-b
    ports:
      - 8082:8080
    environment:
      - VITE_API_URL=http://localhost:4000/api
    depends_on:
      - backend-b
